export const BRAIN_REGIONS = [
  "frontal lobe",
  "parietal lobe",
  "temporal lobe",
  "occipital lobe",
  "insular cortex",
  "anterior cingulate cortex",
  "posterior cingulate cortex",
  "precentral gyrus",
  "postcentral gyrus",
  "superior frontal gyrus",
  "middle frontal gyrus",
  "inferior frontal gyrus",
  "angular gyrus",
  "supramarginal gyrus",
  "fusiform gyrus",
  "parahippocampal gyrus",
  "hippocampus",
  "amygdala",
  "thalamus",
  "hypothalamus",
  "subthalamic nucleus",
  "caudate nucleus",
  "putamen",
  "globus pallidus",
  "striatum",
  "claustrum",
  "nucleus accumbens",
  "substantia nigra",
  "ventral tegmental area",
  "midbrain",
  "pons",
  "medulla oblongata",
  "cerebellar hemisphere",
  "cerebellar vermis",
  "dentate nucleus",
  "interposed nucleus",
  "fastigial nucleus",
  "fornix",
  "mammillary bodies",
  "septal nuclei",
  "olfactory bulb",
  "piriform cortex",
  "entorhinal cortex",
  "perirhinal cortex",
  "retrosplenial cortex",
  "corpus callosum",
  "anterior commissure",
  "internal capsule",
  "corona radiata",
  "superior longitudinal fasciculus",
  "cingulum bundle",
  "uncinate fasciculus",
  "arcuate fasciculus",
  "inferior longitudinal fasciculus",
  "lateral ventricle",
  "third ventricle",
  "fourth ventricle",
  "cerebral aqueduct",
  "choroid plexus",
  "oculomotor nucleus",
  "trochlear nucleus",
  "trigeminal nucleus",
  "abducens nucleus",
  "facial nucleus",
  "vestibulocochlear nucleus",
  "glossopharyngeal nucleus",
  "vagus nucleus",
  "accessory nucleus",
  "hypoglossal nucleus",
  "pineal gland",
  "habenular nuclei",
  "lateral geniculate nucleus",
  "medial geniculate nucleus",
  "pulvinar nucleus",
  "broca's area",
  "wernicke's area",
  "primary motor cortex",
  "primary visual cortex",
  "primary somatosensory cortex",
  "superior parietal lobule",
  "inferior parietal lobule",
  "superior temporal gyrus",
  "middle temporal gyrus",
  "inferior temporal gyrus",
]
